apiVersion: v1
description: A Helm chart for Tekton Pipelines
name: tekton-pipeline
version: 1.0.3
appVersion: 0.65.3
icon: https://avatars2.githubusercontent.com/u/47602533
home: https://github.com/cdfoundation/tekton-helm-chart
